function showPanorama(panoramaImg, titleText)
% SHOWPANORAMA Displays a stitched panorama with formatted annotations
%   Creates a publication-quality figure for the final reconstruction output.
%
% Inputs:
%    panoramaImg - RGB or grayscale panorama image matrix
%    titleText   - (optional) custom title string

    if nargin < 2
        titleText = 'Drone Image Reconstruction — Stitched Panorama';
    end

    figure('Name', 'Panorama Viewer', ...
           'NumberTitle', 'off', ...
           'Color', [0.1 0.1 0.1], ...
           'Position', [50, 100, 1400, 700]);

    imshow(panoramaImg, 'Border', 'tight');

    title(titleText, ...
          'Color', 'w', ...
          'FontSize', 16, ...
          'FontWeight', 'bold', ...
          'Interpreter', 'none');

    % Add resolution annotation
    [h, w, c] = size(panoramaImg);
    annotation('textbox', [0.01 0.01 0.3 0.05], ...
        'String', sprintf('%d × %d px  |  %d channels', w, h, c), ...
        'Color', [0.7 0.7 0.7], ...
        'FontSize', 10, ...
        'EdgeColor', 'none', ...
        'BackgroundColor', 'none');

    drawnow;
    fprintf('Panorama displayed: %d × %d pixels\n', w, h);
end
